name: Deploy to Netlify

on:
  push:
    branches:
      - main  # 當 main 分支有 push 時觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 取得程式碼
        uses: actions/checkout@v3

      - name: 安裝 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 建置網站（若有需要）
        run: echo "無需建置，為純 HTML 專案"

      - name: 部署至 Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: ./public
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "自動部署：${{ github.event.head_commit.message }}"
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        env:
          CI: false
